id: I4BB96AB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T15:28:50+00:00'
last_modified: '2022-06-08T02:59:53.061791+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181143
  title: པོད་ཆེན་དྲུག་རྩ་འགྲེལ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    32C4:
      image_group_id: I4PD3026
      title: ''
      total_pages: 774
      order: 1
      base_file: 32C4.txt
    DD62:
      image_group_id: I4PD3027
      title: ''
      total_pages: 884
      order: 2
      base_file: DD62.txt
    5E7E:
      image_group_id: I4PD3028
      title: ''
      total_pages: 832
      order: 3
      base_file: 5E7E.txt
    D95F:
      image_group_id: I4PD3029
      title: ''
      total_pages: 728
      order: 4
      base_file: D95F.txt
    674B:
      image_group_id: I4PD3030
      title: ''
      total_pages: 718
      order: 5
      base_file: 674B.txt
    365F:
      image_group_id: I4PD3031
      title: ''
      total_pages: 780
      order: 6
      base_file: 365F.txt
    4F4B:
      image_group_id: I4PD3032
      title: ''
      total_pages: 782
      order: 7
      base_file: 4F4B.txt
    806F:
      image_group_id: I4PD3033
      title: ''
      total_pages: 638
      order: 8
      base_file: 806F.txt
    789E:
      image_group_id: I4PD3034
      title: ''
      total_pages: 830
      order: 9
      base_file: 789E.txt
    F41F:
      image_group_id: I4PD3035
      title: ''
      total_pages: 530
      order: 10
      base_file: F41F.txt
    5B2F:
      image_group_id: I4PD3036
      title: ''
      total_pages: 654
      order: 11
      base_file: 5B2F.txt
    CC20:
      image_group_id: I4PD3037
      title: ''
      total_pages: 818
      order: 12
      base_file: CC20.txt
    A4B9:
      image_group_id: I4PD3038
      title: ''
      total_pages: 902
      order: 13
      base_file: A4B9.txt
    '5595':
      image_group_id: I4PD3039
      title: ''
      total_pages: 794
      order: 14
      base_file: 5595.txt
    FDF2:
      image_group_id: I4PD3040
      title: ''
      total_pages: 642
      order: 15
      base_file: FDF2.txt
    DCB2:
      image_group_id: I4PD3041
      title: ''
      total_pages: 722
      order: 16
      base_file: DCB2.txt
    '8981':
      image_group_id: I4PD3042
      title: ''
      total_pages: 530
      order: 17
      base_file: 8981.txt
    DF0F:
      image_group_id: I4PD3043
      title: ''
      total_pages: 790
      order: 18
      base_file: DF0F.txt
    5B12:
      image_group_id: I4PD3044
      title: ''
      total_pages: 754
      order: 19
      base_file: 5B12.txt
    496A:
      image_group_id: I4PD3045
      title: ''
      total_pages: 638
      order: 20
      base_file: 496A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
